# Generated by Django 3.0.6 on 2020-06-16 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_base_multiplier', models.FloatField()),
                ('to_base_adder', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.Type')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_value', models.CharField(max_length=200)),
                ('destination_value', models.CharField(max_length=200)),
                ('destination_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='user_interface.Unit')),
                ('source_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='user_interface.Unit')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.Unit')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.Type')),
            ],
        ),
    ]
